---
# Download and install ZABBIX for Centos/RHEL version 7
- name: Download ZABBIX Repo - Centos/RHEL 7
  get_url: url={{ zabbixRepository }} dest=/tmp/zabbix.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install ZABBIX Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/zabbix.rpm creates=/etc/yum.repos.d/zabbix.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: get {{ zabbixRpmGpgKey }}
  get_url: url={{ zabbixRpmGpgKey }} dest=/tmp/RPM-GPG-KEY-ZABBIX
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Import a key from a file
  rpm_key: state=present key=/tmp/RPM-GPG-KEY-ZABBIX

- name: Install zabbix-agent
  yum: name=zabbix-agent enablerepo=zabbix state=latest disable_gpg_check=no

- name: disabled zabbix repository
  lineinfile: dest=/etc/yum.repos.d/zabbix.repo regexp='^enabled' line="enabled=0"

# Setting zabbix_agentd.conf
- name: Setting zabbix_agentd.conf
  lineinfile: >-
    dest='/etc/zabbix/zabbix_agentd.conf'
    regexp='{{ item.regexp }}'
    insertafter='{{ item.insertafter }}'
    line='{{ item.line }}'
  with_items:
    - regexp: '^ListenPort='
      insertafter: "^# ListenPort="
      line: 'ListenPort={{ ListenPort }}'
    - regexp: '^LogFile='
      insertafter: "^# LogFile="
      line: 'LogFile={{ LogFile }}'
    - regexp: '^Server='
      insertafter: "^# Server="
      line: 'Server={{ Server }}'
    - regexp: '^ServerActive='
      insertafter: "^# ServerActive="
      line: 'ServerActive={{ ServerActive }}'
    - regexp: '^Hostname='
      insertafter: "^# Hostname="
      line: 'Hostname={{ Hostname }}'

- name: start zabbix-agent
  service: name=zabbix-agent state=started enabled=yes
